server:
  port: 8070

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/alibaba_user?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
  application:
    name: user-service
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  main:
    allow-bean-definition-overriding: true #在 Spring Boot 2.1 以及更高的版本增加该设定，因为 Spring Boot 默认调整了 Bean 定义覆盖行为
  redis:
    #Redis服务器地址
    host: 127.0.0.1
    #Redis服务器连接端口
    port: 6379
    password: foobared
    #连接超时时间（毫秒）
    timeout: 10000

#指定日志配置文件，默认是log4j2-spring.xml，推荐使用log4j2.xml
logging:
  config: classpath:log4j2.xml
  level:
    com.alibaba.nacos.client.naming: warn

mybatis:
  #typeAliasesPackage: com.meizu.base.entity
  #指定mapper文件
  mapperLocations: classpath:mapper/**/*Mapper.xml

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

dubbo:
  registry:
#    address: nacos://127.0.0.1:8848 #注册中心地址
    address: spring-cloud://127.0.0.1 #挂载到Spring Cloud注册中心
    timeout: 10000 #指定注册到nacos上超时时间，ms
  protocol:
    name: dubbo #Dubbo的协议名称
    port: -1 #port为协议端口（ -1 表示自增端口，从 20880 开始）
  consumer:
    check: false #@DubboReference启动校验
  cloud:
    subscribed-services: order-service,mail-service

