server:
  port: 8071

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/alibaba_order?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
  application:
    name: order-service
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 #nacos中心地址
  main:
    allow-bean-definition-overriding: true #在 Spring Boot 2.1 以及更高的版本增加该设定，因为 Spring Boot 默认调整了 Bean 定义覆盖行为
  redis:
    host: 127.0.0.1 #Redis服务器地址
    port: 6379 #Redis服务器连接端口
    password: foobared
    timeout: 10000 #连接超时时间（毫秒）

#指定日志配置文件，默认是log4j2-spring.xml，推荐使用log4j2.xml
logging:
  config: classpath:log4j2.xml
  level:
    com.alibaba.nacos.client.naming: warn

#mybatis配置
mybatis:
  #typeAliasesPackage: com.meizu.base.entity
  #指定mapper文件
  mapperLocations: classpath:mapper/**/*Mapper.xml

#分页插件配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

#dubbo配置
dubbo:
  registry:
#    address: nacos://127.0.0.1:8848 #注册中心地址
    address: spring-cloud://127.0.0.1 #挂载到Spring Cloud注册中心
    timeout: 10000 #指定注册到nacos上超时时间，ms
  protocol:
    name: dubbo #Dubbo的协议名称
    port: -1 #port为协议端口（ -1 表示自增端口，从 20880 开始）
  consumer:
    check: false #@DubboReference启动校验
  cloud:
    subscribed-services: user-service,mail-service

#seata配置
seata:
  enabled: true
  application-id: ${spring.application.name}
  tx-service-group: my_tx_group_test
  service:
    vgroup-mapping:
      my_tx_group_test: default
    grouplist:
      default: 172.16.180.93:8091

#rockermq配置
rocketmq:
  #rocketmq的NameServer地址
  name-server: 172.16.180.93:9876
  # 生产者端配置
  producer:
    group: my_test_producer_group
  consumer:
    group: my_test_consumer_group
  topic:
    mail: mail_topic


